version: '3'

services:
  db:
    image: postgres:14.2
    restart: "no"
    ports:
      -  5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cellmap
      - POSTGRES_PASSWORD=admin