"""add indices

Revision ID: 3b1f69ed5bd9
Revises: 410ba6718e3c
Create Date: 2022-09-12 21:49:01.548308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1f69ed5bd9'
down_revision = '410ba6718e3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_view_id'), 'view', ['id'], unique=False)
    op.create_index(op.f('ix_view_to_volume_view_id'), 'view_to_volume', ['view_id'], unique=False)
    op.create_index(op.f('ix_view_to_volume_volume_id'), 'view_to_volume', ['volume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_to_volume_volume_id'), table_name='view_to_volume')
    op.drop_index(op.f('ix_view_to_volume_view_id'), table_name='view_to_volume')
    op.drop_index(op.f('ix_view_id'), table_name='view')
    # ### end Alembic commands ###
