"""add more cascade rules

Revision ID: 4344423fffe3
Revises: 9df896e316cc
Create Date: 2022-10-07 11:26:24.143748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4344423fffe3"
down_revision = "9df896e316cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("image_dataset_name_fkey", "image", type_="foreignkey")
    op.create_foreign_key(
        None, "image", "dataset", ["dataset_name"], ["name"], ondelete="CASCADE"
    )
    op.drop_constraint("view_dataset_name_fkey", "view", type_="foreignkey")
    op.create_foreign_key(
        None, "view", "dataset", ["dataset_name"], ["name"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "view", type_="foreignkey")
    op.create_foreign_key(
        "view_dataset_name_fkey", "view", "dataset", ["dataset_name"], ["name"]
    )
    op.drop_constraint(None, "image", type_="foreignkey")
    op.create_foreign_key(
        "image_dataset_name_fkey", "image", "dataset", ["dataset_name"], ["name"]
    )
    # ### end Alembic commands ###
