"""add cascade rules

Revision ID: 9df896e316cc
Revises: 96186bb0acca
Create Date: 2022-10-07 00:18:13.783000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9df896e316cc"
down_revision = "96186bb0acca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
