"""cascades

Revision ID: ecc545164a39
Revises: 4344423fffe3
Create Date: 2022-10-07 13:07:08.400735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ecc545164a39"
down_revision = "4344423fffe3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("crop_source_id_fkey", "crop", type_="foreignkey")
    op.create_foreign_key(
        None, "crop", "image", ["source_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("dataset_sample_id_fkey", "dataset", type_="foreignkey")
    op.drop_constraint("dataset_acquisition_id_fkey", "dataset", type_="foreignkey")
    op.create_foreign_key(
        None, "dataset", "sample", ["sample_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "dataset",
        "fibsem_acquisition",
        ["acquisition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("labelclass_crop_id_fkey", "labelclass", type_="foreignkey")
    op.create_foreign_key(
        None, "labelclass", "crop", ["crop_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "publication_to_dataset_publication_id_fkey",
        "publication_to_dataset",
        type_="foreignkey",
    )
    op.drop_constraint(
        "publication_to_dataset_dataset_id_fkey",
        "publication_to_dataset",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "publication_to_dataset",
        "dataset",
        ["dataset_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "publication_to_dataset",
        "publication",
        ["publication_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "view_to_image_image_id_fkey", "view_to_image", type_="foreignkey"
    )
    op.drop_constraint(
        "view_to_image_view_id_fkey", "view_to_image", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "view_to_image", "image", ["image_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "view_to_image", "view", ["view_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "view_to_image", type_="foreignkey")
    op.drop_constraint(None, "view_to_image", type_="foreignkey")
    op.create_foreign_key(
        "view_to_image_view_id_fkey", "view_to_image", "view", ["view_id"], ["id"]
    )
    op.create_foreign_key(
        "view_to_image_image_id_fkey", "view_to_image", "image", ["image_id"], ["id"]
    )
    op.drop_constraint(None, "publication_to_dataset", type_="foreignkey")
    op.drop_constraint(None, "publication_to_dataset", type_="foreignkey")
    op.create_foreign_key(
        "publication_to_dataset_dataset_id_fkey",
        "publication_to_dataset",
        "dataset",
        ["dataset_id"],
        ["id"],
    )
    op.create_foreign_key(
        "publication_to_dataset_publication_id_fkey",
        "publication_to_dataset",
        "publication",
        ["publication_id"],
        ["id"],
    )
    op.drop_constraint(None, "labelclass", type_="foreignkey")
    op.create_foreign_key(
        "labelclass_crop_id_fkey", "labelclass", "crop", ["crop_id"], ["id"]
    )
    op.drop_constraint(None, "dataset", type_="foreignkey")
    op.drop_constraint(None, "dataset", type_="foreignkey")
    op.create_foreign_key(
        "dataset_acquisition_id_fkey",
        "dataset",
        "fibsem_acquisition",
        ["acquisition_id"],
        ["id"],
    )
    op.create_foreign_key(
        "dataset_sample_id_fkey", "dataset", "sample", ["sample_id"], ["id"]
    )
    op.drop_constraint(None, "crop", type_="foreignkey")
    op.create_foreign_key("crop_source_id_fkey", "crop", "image", ["source_id"], ["id"])
    # ### end Alembic commands ###
